#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 198
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 77
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 14

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  sym_number = 3,
  anon_sym_struct = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_COLON = 7,
  anon_sym_enum = 8,
  anon_sym_Copy = 9,
  anon_sym_Drop = 10,
  anon_sym_SEMI = 11,
  anon_sym_extern = 12,
  anon_sym_fn = 13,
  anon_sym_LPAREN = 14,
  anon_sym_COMMA = 15,
  anon_sym_RPAREN = 16,
  anon_sym_EQ = 17,
  anon_sym_call = 18,
  anon_sym_goto = 19,
  sym_return = 20,
  anon_sym_branch = 21,
  anon_sym_LBRACK = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  anon_sym_RBRACK = 25,
  anon_sym_switchEnum = 26,
  sym_abort = 27,
  sym_unreachable = 28,
  anon_sym_DOT = 29,
  anon_sym_as = 30,
  anon_sym_payload = 31,
  anon_sym_STAR = 32,
  anon_sym_copy = 33,
  anon_sym_move = 34,
  anon_sym_AMP = 35,
  anon_sym_AMPmut = 36,
  anon_sym_AMPout = 37,
  anon_sym_AMPdrop = 38,
  anon_sym_AMPuninit = 39,
  anon_sym_COLON_COLON = 40,
  anon_sym_number = 41,
  anon_sym_boolean = 42,
  sym_program = 43,
  sym_declaration = 44,
  sym_struct_decl = 45,
  sym_struct_field = 46,
  sym_enum_decl = 47,
  sym_enum_variant = 48,
  sym_markers = 49,
  sym_param_decl = 50,
  sym_local_decl = 51,
  sym_function_decl = 52,
  sym_basic_block = 53,
  sym_statement = 54,
  sym_assignment = 55,
  sym_call = 56,
  sym_terminator = 57,
  sym_goto = 58,
  sym_branch = 59,
  sym_switchEnum = 60,
  sym_switch_case = 61,
  sym_place = 62,
  sym_operand = 63,
  sym_const = 64,
  sym_rvalue = 65,
  sym_type = 66,
  aux_sym_program_repeat1 = 67,
  aux_sym_struct_decl_repeat1 = 68,
  aux_sym_enum_decl_repeat1 = 69,
  aux_sym_function_decl_repeat1 = 70,
  aux_sym_function_decl_repeat2 = 71,
  aux_sym_function_decl_repeat3 = 72,
  aux_sym_basic_block_repeat1 = 73,
  aux_sym_call_repeat1 = 74,
  aux_sym_switchEnum_repeat1 = 75,
  aux_sym_type_repeat1 = 76,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_enum] = "enum",
  [anon_sym_Copy] = "Copy",
  [anon_sym_Drop] = "Drop",
  [anon_sym_SEMI] = ";",
  [anon_sym_extern] = "extern",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_call] = "call",
  [anon_sym_goto] = "goto",
  [sym_return] = "return",
  [anon_sym_branch] = "branch",
  [anon_sym_LBRACK] = "[",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_RBRACK] = "]",
  [anon_sym_switchEnum] = "switchEnum",
  [sym_abort] = "abort",
  [sym_unreachable] = "unreachable",
  [anon_sym_DOT] = ".",
  [anon_sym_as] = "as",
  [anon_sym_payload] = "payload",
  [anon_sym_STAR] = "*",
  [anon_sym_copy] = "copy",
  [anon_sym_move] = "move",
  [anon_sym_AMP] = "&",
  [anon_sym_AMPmut] = "&mut",
  [anon_sym_AMPout] = "&out",
  [anon_sym_AMPdrop] = "&drop",
  [anon_sym_AMPuninit] = "&uninit",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_number] = "number",
  [anon_sym_boolean] = "boolean",
  [sym_program] = "program",
  [sym_declaration] = "declaration",
  [sym_struct_decl] = "struct_decl",
  [sym_struct_field] = "struct_field",
  [sym_enum_decl] = "enum_decl",
  [sym_enum_variant] = "enum_variant",
  [sym_markers] = "markers",
  [sym_param_decl] = "param_decl",
  [sym_local_decl] = "local_decl",
  [sym_function_decl] = "function_decl",
  [sym_basic_block] = "basic_block",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_call] = "call",
  [sym_terminator] = "terminator",
  [sym_goto] = "goto",
  [sym_branch] = "branch",
  [sym_switchEnum] = "switchEnum",
  [sym_switch_case] = "switch_case",
  [sym_place] = "place",
  [sym_operand] = "operand",
  [sym_const] = "const",
  [sym_rvalue] = "rvalue",
  [sym_type] = "type",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_struct_decl_repeat1] = "struct_decl_repeat1",
  [aux_sym_enum_decl_repeat1] = "enum_decl_repeat1",
  [aux_sym_function_decl_repeat1] = "function_decl_repeat1",
  [aux_sym_function_decl_repeat2] = "function_decl_repeat2",
  [aux_sym_function_decl_repeat3] = "function_decl_repeat3",
  [aux_sym_basic_block_repeat1] = "basic_block_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_switchEnum_repeat1] = "switchEnum_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_Copy] = anon_sym_Copy,
  [anon_sym_Drop] = anon_sym_Drop,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_goto] = anon_sym_goto,
  [sym_return] = sym_return,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_switchEnum] = anon_sym_switchEnum,
  [sym_abort] = sym_abort,
  [sym_unreachable] = sym_unreachable,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_payload] = anon_sym_payload,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_copy] = anon_sym_copy,
  [anon_sym_move] = anon_sym_move,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_AMPmut] = anon_sym_AMPmut,
  [anon_sym_AMPout] = anon_sym_AMPout,
  [anon_sym_AMPdrop] = anon_sym_AMPdrop,
  [anon_sym_AMPuninit] = anon_sym_AMPuninit,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_boolean] = anon_sym_boolean,
  [sym_program] = sym_program,
  [sym_declaration] = sym_declaration,
  [sym_struct_decl] = sym_struct_decl,
  [sym_struct_field] = sym_struct_field,
  [sym_enum_decl] = sym_enum_decl,
  [sym_enum_variant] = sym_enum_variant,
  [sym_markers] = sym_markers,
  [sym_param_decl] = sym_param_decl,
  [sym_local_decl] = sym_local_decl,
  [sym_function_decl] = sym_function_decl,
  [sym_basic_block] = sym_basic_block,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_call] = sym_call,
  [sym_terminator] = sym_terminator,
  [sym_goto] = sym_goto,
  [sym_branch] = sym_branch,
  [sym_switchEnum] = sym_switchEnum,
  [sym_switch_case] = sym_switch_case,
  [sym_place] = sym_place,
  [sym_operand] = sym_operand,
  [sym_const] = sym_const,
  [sym_rvalue] = sym_rvalue,
  [sym_type] = sym_type,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_struct_decl_repeat1] = aux_sym_struct_decl_repeat1,
  [aux_sym_enum_decl_repeat1] = aux_sym_enum_decl_repeat1,
  [aux_sym_function_decl_repeat1] = aux_sym_function_decl_repeat1,
  [aux_sym_function_decl_repeat2] = aux_sym_function_decl_repeat2,
  [aux_sym_function_decl_repeat3] = aux_sym_function_decl_repeat3,
  [aux_sym_basic_block_repeat1] = aux_sym_basic_block_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_switchEnum_repeat1] = aux_sym_switchEnum_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Drop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goto] = {
    .visible = true,
    .named = false,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_switchEnum] = {
    .visible = true,
    .named = false,
  },
  [sym_abort] = {
    .visible = true,
    .named = true,
  },
  [sym_unreachable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_payload] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_move] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPmut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPdrop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPuninit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_markers] = {
    .visible = true,
    .named = true,
  },
  [sym_param_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_local_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_basic_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_terminator] = {
    .visible = true,
    .named = true,
  },
  [sym_goto] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_switchEnum] = {
    .visible = true,
    .named = true,
  },
  [sym_switch_case] = {
    .visible = true,
    .named = true,
  },
  [sym_place] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_rvalue] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_basic_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_switchEnum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_enum_name = 2,
  field_false_label = 3,
  field_field = 4,
  field_function = 5,
  field_label = 6,
  field_lhs = 7,
  field_name = 8,
  field_place = 9,
  field_rhs = 10,
  field_true_label = 11,
  field_type = 12,
  field_variant = 13,
  field_variant_name = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_enum_name] = "enum_name",
  [field_false_label] = "false_label",
  [field_field] = "field",
  [field_function] = "function",
  [field_label] = "label",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_place] = "place",
  [field_rhs] = "rhs",
  [field_true_label] = "true_label",
  [field_type] = "type",
  [field_variant] = "variant",
  [field_variant_name] = "variant_name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 11, .length = 1},
  [11] = {.index = 12, .length = 2},
  [12] = {.index = 14, .length = 2},
  [13] = {.index = 16, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 2},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_label, 0},
  [5] =
    {field_label, 1},
  [6] =
    {field_lhs, 0},
    {field_rhs, 2},
  [8] =
    {field_field, 2},
  [9] =
    {field_function, 1},
  [10] =
    {field_place, 2},
  [11] =
    {field_variant, 3},
  [12] =
    {field_label, 2},
    {field_variant, 0},
  [14] =
    {field_enum_name, 0},
    {field_variant_name, 2},
  [16] =
    {field_condition, 2},
    {field_false_label, 11},
    {field_true_label, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 183,
  [184] = 184,
  [185] = 185,
  [186] = 186,
  [187] = 187,
  [188] = 188,
  [189] = 189,
  [190] = 190,
  [191] = 191,
  [192] = 192,
  [193] = 193,
  [194] = 194,
  [195] = 195,
  [196] = 196,
  [197] = 197,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '#', 17,
        '&', 33,
        '(', 25,
        ')', 27,
        '*', 32,
        ',', 26,
        '.', 31,
        ':', 23,
        ';', 24,
        '=', 28,
        '[', 29,
        ']', 30,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ';') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == ':') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'm') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMPmut);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_AMPout);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AMPdrop);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AMPuninit);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'D', 2,
        'a', 3,
        'b', 4,
        'c', 5,
        'e', 6,
        'f', 7,
        'g', 8,
        'm', 9,
        'n', 10,
        'p', 11,
        'r', 12,
        's', 13,
        't', 14,
        'u', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'b') ADVANCE(18);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'w') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'v') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 31:
      if (lookahead == 'y') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(56);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 43:
      if (lookahead == 'y') ADVANCE(62);
      END_STATE();
    case 44:
      if (lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(66);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 49:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(71);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_Copy);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_Drop);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 60:
      if (lookahead == 'c') ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_goto);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_move);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 71:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 72:
      if (lookahead == 'c') ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_abort);
      END_STATE();
    case 76:
      if (lookahead == 'a') ADVANCE(86);
      END_STATE();
    case 77:
      if (lookahead == 'h') ADVANCE(87);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(90);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 84:
      if (lookahead == 'h') ADVANCE(93);
      END_STATE();
    case 85:
      if (lookahead == 'c') ADVANCE(94);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 90:
      if (lookahead == 'd') ADVANCE(96);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_return);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 93:
      if (lookahead == 'E') ADVANCE(97);
      END_STATE();
    case 94:
      if (lookahead == 'h') ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_payload);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 98:
      if (lookahead == 'a') ADVANCE(100);
      END_STATE();
    case 99:
      if (lookahead == 'u') ADVANCE(101);
      END_STATE();
    case 100:
      if (lookahead == 'b') ADVANCE(102);
      END_STATE();
    case 101:
      if (lookahead == 'm') ADVANCE(103);
      END_STATE();
    case 102:
      if (lookahead == 'l') ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_switchEnum);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_unreachable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 2},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 2},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 2},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 2},
  [176] = {.lex_state = 2},
  [177] = {.lex_state = 2},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
  [183] = {.lex_state = 0},
  [184] = {.lex_state = 0},
  [185] = {.lex_state = 0},
  [186] = {.lex_state = 0},
  [187] = {.lex_state = 0},
  [188] = {.lex_state = 0},
  [189] = {.lex_state = 0},
  [190] = {.lex_state = 0},
  [191] = {.lex_state = 2},
  [192] = {.lex_state = 0},
  [193] = {.lex_state = 0},
  [194] = {.lex_state = 2},
  [195] = {.lex_state = 0},
  [196] = {.lex_state = 0},
  [197] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_Copy] = ACTIONS(1),
    [anon_sym_Drop] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_goto] = ACTIONS(1),
    [sym_return] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_switchEnum] = ACTIONS(1),
    [sym_abort] = ACTIONS(1),
    [sym_unreachable] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_payload] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [anon_sym_move] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_AMPmut] = ACTIONS(1),
    [anon_sym_AMPout] = ACTIONS(1),
    [anon_sym_AMPdrop] = ACTIONS(1),
    [anon_sym_AMPuninit] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(154),
    [sym_declaration] = STATE(10),
    [sym_struct_decl] = STATE(42),
    [sym_enum_decl] = STATE(42),
    [sym_function_decl] = STATE(42),
    [aux_sym_program_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_struct] = ACTIONS(7),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_call,
    ACTIONS(23), 1,
      anon_sym_goto,
    ACTIONS(27), 1,
      anon_sym_branch,
    ACTIONS(29), 1,
      anon_sym_switchEnum,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(3), 1,
      aux_sym_basic_block_repeat1,
    STATE(116), 1,
      sym_terminator,
    STATE(118), 1,
      sym_place,
    STATE(180), 1,
      sym_type,
    STATE(184), 1,
      sym_statement,
    ACTIONS(37), 2,
      anon_sym_number,
      anon_sym_boolean,
    STATE(183), 2,
      sym_assignment,
      sym_call,
    ACTIONS(25), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(123), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [70] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_call,
    ACTIONS(23), 1,
      anon_sym_goto,
    ACTIONS(27), 1,
      anon_sym_branch,
    ACTIONS(29), 1,
      anon_sym_switchEnum,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(5), 1,
      aux_sym_basic_block_repeat1,
    STATE(118), 1,
      sym_place,
    STATE(133), 1,
      sym_terminator,
    STATE(184), 1,
      sym_statement,
    STATE(183), 2,
      sym_assignment,
      sym_call,
    ACTIONS(25), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(123), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
  [121] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_call,
    ACTIONS(23), 1,
      anon_sym_goto,
    ACTIONS(27), 1,
      anon_sym_branch,
    ACTIONS(29), 1,
      anon_sym_switchEnum,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(3), 1,
      aux_sym_basic_block_repeat1,
    STATE(116), 1,
      sym_terminator,
    STATE(118), 1,
      sym_place,
    STATE(184), 1,
      sym_statement,
    STATE(183), 2,
      sym_assignment,
      sym_call,
    ACTIONS(25), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(123), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
  [172] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_call,
    ACTIONS(52), 1,
      anon_sym_STAR,
    STATE(5), 1,
      aux_sym_basic_block_repeat1,
    STATE(118), 1,
      sym_place,
    STATE(184), 1,
      sym_statement,
    STATE(183), 2,
      sym_assignment,
      sym_call,
    ACTIONS(50), 6,
      anon_sym_goto,
      sym_return,
      anon_sym_branch,
      anon_sym_switchEnum,
      sym_abort,
      sym_unreachable,
  [209] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(63), 1,
      anon_sym_AMP,
    STATE(84), 1,
      sym_const,
    STATE(152), 1,
      sym_operand,
    STATE(153), 1,
      sym_rvalue,
    ACTIONS(59), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(65), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [245] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [272] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(138), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [296] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(140), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [320] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_struct,
    ACTIONS(9), 1,
      anon_sym_enum,
    ACTIONS(11), 1,
      anon_sym_extern,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(14), 2,
      sym_declaration,
      aux_sym_program_repeat1,
    STATE(42), 3,
      sym_struct_decl,
      sym_enum_decl,
      sym_function_decl,
  [348] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(180), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_LPAREN,
      anon_sym_STAR,
    ACTIONS(50), 8,
      sym_identifier,
      anon_sym_call,
      anon_sym_goto,
      sym_return,
      anon_sym_branch,
      anon_sym_switchEnum,
      sym_abort,
      sym_unreachable,
  [390] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(142), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [414] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      anon_sym_struct,
    ACTIONS(78), 1,
      anon_sym_enum,
    ACTIONS(81), 1,
      anon_sym_extern,
    ACTIONS(84), 1,
      anon_sym_fn,
    STATE(14), 2,
      sym_declaration,
      aux_sym_program_repeat1,
    STATE(42), 3,
      sym_struct_decl,
      sym_enum_decl,
      sym_function_decl,
  [442] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(136), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [466] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(58), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [490] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_const,
    STATE(100), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [515] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(84), 1,
      sym_const,
    STATE(148), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [537] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(84), 1,
      sym_const,
    STATE(114), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [559] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(84), 1,
      sym_const,
    STATE(163), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [581] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(84), 1,
      sym_const,
    STATE(186), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(89), 6,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_as,
  [618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [631] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [657] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [675] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(33), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(65), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [693] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(67), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [711] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(37), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [729] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(35), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(93), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [747] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(93), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [765] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(83), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [783] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [801] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [819] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [837] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(34), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(88), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [855] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(70), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [873] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(117), 4,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [919] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [974] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [985] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [996] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1029] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1062] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1172] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 4,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1196] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_identifier,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1224] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(82), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1238] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_identifier,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1252] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(69), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1266] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(81), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1280] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_Copy,
    ACTIONS(191), 1,
      anon_sym_Drop,
    STATE(155), 1,
      sym_markers,
  [1296] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(22), 1,
      sym_place,
  [1312] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1326] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(121), 1,
      sym_place,
  [1342] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    STATE(79), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1356] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(143), 1,
      sym_place,
  [1372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(90), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1386] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(38), 1,
      sym_place,
  [1402] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    STATE(82), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1416] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(82), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 4,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1454] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    STATE(90), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1468] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(86), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [1482] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(85), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1496] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1510] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(122), 1,
      sym_place,
  [1526] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(90), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1540] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1554] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_Copy,
    ACTIONS(191), 1,
      anon_sym_Drop,
    ACTIONS(229), 1,
      sym_identifier,
    STATE(147), 1,
      sym_markers,
  [1570] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(91), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      aux_sym_function_decl_repeat1,
  [1597] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      sym_param_decl,
  [1610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(111), 1,
      aux_sym_type_repeat1,
  [1623] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_SEMI,
    ACTIONS(93), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1634] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_function_decl_repeat1,
  [1647] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(107), 1,
      sym_param_decl,
  [1660] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      aux_sym_call_repeat1,
  [1673] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      aux_sym_switchEnum_repeat1,
  [1686] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      aux_sym_switchEnum_repeat1,
  [1699] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_function_decl_repeat1,
  [1712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_function_decl_repeat1,
  [1725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      aux_sym_switchEnum_repeat1,
  [1738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      aux_sym_call_repeat1,
  [1751] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(104), 1,
      aux_sym_function_decl_repeat1,
  [1764] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(108), 1,
      aux_sym_type_repeat1,
  [1777] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
    ACTIONS(283), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      sym_switch_case,
  [1790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      aux_sym_call_repeat1,
  [1803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(108), 1,
      aux_sym_type_repeat1,
  [1816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1824] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
    STATE(125), 1,
      sym_switch_case,
  [1834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1858] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_LBRACE,
    ACTIONS(297), 1,
      anon_sym_SEMI,
  [1868] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(299), 1,
      anon_sym_EQ,
  [1878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1886] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    ACTIONS(303), 1,
      anon_sym_COLON_COLON,
  [1896] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(305), 1,
      anon_sym_SEMI,
  [1906] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(307), 1,
      anon_sym_as,
  [1916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1940] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1956] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_SEMI,
    ACTIONS(317), 1,
      anon_sym_LBRACE,
  [1966] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_SEMI,
    ACTIONS(319), 1,
      anon_sym_LBRACE,
  [1976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1984] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_LBRACE,
    ACTIONS(323), 1,
      anon_sym_SEMI,
  [1994] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [2002] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [2010] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
    ACTIONS(331), 1,
      anon_sym_Copy,
  [2020] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
    ACTIONS(331), 1,
      anon_sym_Drop,
  [2030] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
  [2048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2056] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(130), 1,
      sym_param_decl,
  [2066] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [2074] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_SEMI,
    ACTIONS(339), 1,
      anon_sym_LBRACE,
  [2084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [2092] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_DOT,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
  [2102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_LBRACE,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      sym_identifier,
  [2116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_LBRACE,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_identifier,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_RPAREN,
  [2137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_COLON,
  [2144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      sym_identifier,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LPAREN,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_SEMI,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      ts_builtin_sym_end,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym_identifier,
  [2186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_COLON,
  [2193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_RPAREN,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_SEMI,
  [2207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      sym_identifier,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      anon_sym_LBRACK,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_LBRACK,
  [2228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      sym_identifier,
  [2235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_LPAREN,
  [2242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      anon_sym_DOT,
  [2249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      sym_identifier,
  [2256] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      anon_sym_SEMI,
  [2263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_LPAREN,
  [2270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_true,
  [2277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_COLON,
  [2284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_LPAREN,
  [2291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      anon_sym_payload,
  [2298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      sym_identifier,
  [2305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_SEMI,
  [2312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_LBRACE,
  [2319] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_COLON,
  [2326] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_COLON,
  [2333] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      anon_sym_COLON,
  [2340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_LBRACE,
  [2347] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      anon_sym_fn,
  [2354] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      anon_sym_SEMI,
  [2361] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(419), 1,
      sym_identifier,
  [2368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(421), 1,
      sym_identifier,
  [2375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(423), 1,
      anon_sym_SEMI,
  [2382] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(425), 1,
      anon_sym_SEMI,
  [2389] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(427), 1,
      anon_sym_LPAREN,
  [2396] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(429), 1,
      anon_sym_RPAREN,
  [2403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(431), 1,
      anon_sym_COMMA,
  [2410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(433), 1,
      anon_sym_LPAREN,
  [2417] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(435), 1,
      sym_identifier,
  [2424] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(437), 1,
      anon_sym_LPAREN,
  [2431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(439), 1,
      anon_sym_COLON,
  [2438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(441), 1,
      anon_sym_SEMI,
  [2445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(443), 1,
      anon_sym_false,
  [2452] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(445), 1,
      anon_sym_COLON,
  [2459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(447), 1,
      sym_identifier,
  [2466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(449), 1,
      anon_sym_RBRACK,
  [2473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(451), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 70,
  [SMALL_STATE(4)] = 121,
  [SMALL_STATE(5)] = 172,
  [SMALL_STATE(6)] = 209,
  [SMALL_STATE(7)] = 245,
  [SMALL_STATE(8)] = 272,
  [SMALL_STATE(9)] = 296,
  [SMALL_STATE(10)] = 320,
  [SMALL_STATE(11)] = 348,
  [SMALL_STATE(12)] = 372,
  [SMALL_STATE(13)] = 390,
  [SMALL_STATE(14)] = 414,
  [SMALL_STATE(15)] = 442,
  [SMALL_STATE(16)] = 466,
  [SMALL_STATE(17)] = 490,
  [SMALL_STATE(18)] = 515,
  [SMALL_STATE(19)] = 537,
  [SMALL_STATE(20)] = 559,
  [SMALL_STATE(21)] = 581,
  [SMALL_STATE(22)] = 603,
  [SMALL_STATE(23)] = 618,
  [SMALL_STATE(24)] = 631,
  [SMALL_STATE(25)] = 644,
  [SMALL_STATE(26)] = 657,
  [SMALL_STATE(27)] = 675,
  [SMALL_STATE(28)] = 693,
  [SMALL_STATE(29)] = 711,
  [SMALL_STATE(30)] = 729,
  [SMALL_STATE(31)] = 747,
  [SMALL_STATE(32)] = 765,
  [SMALL_STATE(33)] = 783,
  [SMALL_STATE(34)] = 801,
  [SMALL_STATE(35)] = 819,
  [SMALL_STATE(36)] = 837,
  [SMALL_STATE(37)] = 855,
  [SMALL_STATE(38)] = 873,
  [SMALL_STATE(39)] = 886,
  [SMALL_STATE(40)] = 897,
  [SMALL_STATE(41)] = 908,
  [SMALL_STATE(42)] = 919,
  [SMALL_STATE(43)] = 930,
  [SMALL_STATE(44)] = 941,
  [SMALL_STATE(45)] = 952,
  [SMALL_STATE(46)] = 963,
  [SMALL_STATE(47)] = 974,
  [SMALL_STATE(48)] = 985,
  [SMALL_STATE(49)] = 996,
  [SMALL_STATE(50)] = 1007,
  [SMALL_STATE(51)] = 1018,
  [SMALL_STATE(52)] = 1029,
  [SMALL_STATE(53)] = 1040,
  [SMALL_STATE(54)] = 1051,
  [SMALL_STATE(55)] = 1062,
  [SMALL_STATE(56)] = 1073,
  [SMALL_STATE(57)] = 1084,
  [SMALL_STATE(58)] = 1095,
  [SMALL_STATE(59)] = 1106,
  [SMALL_STATE(60)] = 1117,
  [SMALL_STATE(61)] = 1128,
  [SMALL_STATE(62)] = 1139,
  [SMALL_STATE(63)] = 1150,
  [SMALL_STATE(64)] = 1161,
  [SMALL_STATE(65)] = 1172,
  [SMALL_STATE(66)] = 1186,
  [SMALL_STATE(67)] = 1196,
  [SMALL_STATE(68)] = 1210,
  [SMALL_STATE(69)] = 1224,
  [SMALL_STATE(70)] = 1238,
  [SMALL_STATE(71)] = 1252,
  [SMALL_STATE(72)] = 1266,
  [SMALL_STATE(73)] = 1280,
  [SMALL_STATE(74)] = 1296,
  [SMALL_STATE(75)] = 1312,
  [SMALL_STATE(76)] = 1326,
  [SMALL_STATE(77)] = 1342,
  [SMALL_STATE(78)] = 1356,
  [SMALL_STATE(79)] = 1372,
  [SMALL_STATE(80)] = 1386,
  [SMALL_STATE(81)] = 1402,
  [SMALL_STATE(82)] = 1416,
  [SMALL_STATE(83)] = 1430,
  [SMALL_STATE(84)] = 1444,
  [SMALL_STATE(85)] = 1454,
  [SMALL_STATE(86)] = 1468,
  [SMALL_STATE(87)] = 1482,
  [SMALL_STATE(88)] = 1496,
  [SMALL_STATE(89)] = 1510,
  [SMALL_STATE(90)] = 1526,
  [SMALL_STATE(91)] = 1540,
  [SMALL_STATE(92)] = 1554,
  [SMALL_STATE(93)] = 1570,
  [SMALL_STATE(94)] = 1584,
  [SMALL_STATE(95)] = 1597,
  [SMALL_STATE(96)] = 1610,
  [SMALL_STATE(97)] = 1623,
  [SMALL_STATE(98)] = 1634,
  [SMALL_STATE(99)] = 1647,
  [SMALL_STATE(100)] = 1660,
  [SMALL_STATE(101)] = 1673,
  [SMALL_STATE(102)] = 1686,
  [SMALL_STATE(103)] = 1699,
  [SMALL_STATE(104)] = 1712,
  [SMALL_STATE(105)] = 1725,
  [SMALL_STATE(106)] = 1738,
  [SMALL_STATE(107)] = 1751,
  [SMALL_STATE(108)] = 1764,
  [SMALL_STATE(109)] = 1777,
  [SMALL_STATE(110)] = 1790,
  [SMALL_STATE(111)] = 1803,
  [SMALL_STATE(112)] = 1816,
  [SMALL_STATE(113)] = 1824,
  [SMALL_STATE(114)] = 1834,
  [SMALL_STATE(115)] = 1842,
  [SMALL_STATE(116)] = 1850,
  [SMALL_STATE(117)] = 1858,
  [SMALL_STATE(118)] = 1868,
  [SMALL_STATE(119)] = 1878,
  [SMALL_STATE(120)] = 1886,
  [SMALL_STATE(121)] = 1896,
  [SMALL_STATE(122)] = 1906,
  [SMALL_STATE(123)] = 1916,
  [SMALL_STATE(124)] = 1924,
  [SMALL_STATE(125)] = 1932,
  [SMALL_STATE(126)] = 1940,
  [SMALL_STATE(127)] = 1948,
  [SMALL_STATE(128)] = 1956,
  [SMALL_STATE(129)] = 1966,
  [SMALL_STATE(130)] = 1976,
  [SMALL_STATE(131)] = 1984,
  [SMALL_STATE(132)] = 1994,
  [SMALL_STATE(133)] = 2002,
  [SMALL_STATE(134)] = 2010,
  [SMALL_STATE(135)] = 2020,
  [SMALL_STATE(136)] = 2030,
  [SMALL_STATE(137)] = 2038,
  [SMALL_STATE(138)] = 2048,
  [SMALL_STATE(139)] = 2056,
  [SMALL_STATE(140)] = 2066,
  [SMALL_STATE(141)] = 2074,
  [SMALL_STATE(142)] = 2084,
  [SMALL_STATE(143)] = 2092,
  [SMALL_STATE(144)] = 2102,
  [SMALL_STATE(145)] = 2109,
  [SMALL_STATE(146)] = 2116,
  [SMALL_STATE(147)] = 2123,
  [SMALL_STATE(148)] = 2130,
  [SMALL_STATE(149)] = 2137,
  [SMALL_STATE(150)] = 2144,
  [SMALL_STATE(151)] = 2151,
  [SMALL_STATE(152)] = 2158,
  [SMALL_STATE(153)] = 2165,
  [SMALL_STATE(154)] = 2172,
  [SMALL_STATE(155)] = 2179,
  [SMALL_STATE(156)] = 2186,
  [SMALL_STATE(157)] = 2193,
  [SMALL_STATE(158)] = 2200,
  [SMALL_STATE(159)] = 2207,
  [SMALL_STATE(160)] = 2214,
  [SMALL_STATE(161)] = 2221,
  [SMALL_STATE(162)] = 2228,
  [SMALL_STATE(163)] = 2235,
  [SMALL_STATE(164)] = 2242,
  [SMALL_STATE(165)] = 2249,
  [SMALL_STATE(166)] = 2256,
  [SMALL_STATE(167)] = 2263,
  [SMALL_STATE(168)] = 2270,
  [SMALL_STATE(169)] = 2277,
  [SMALL_STATE(170)] = 2284,
  [SMALL_STATE(171)] = 2291,
  [SMALL_STATE(172)] = 2298,
  [SMALL_STATE(173)] = 2305,
  [SMALL_STATE(174)] = 2312,
  [SMALL_STATE(175)] = 2319,
  [SMALL_STATE(176)] = 2326,
  [SMALL_STATE(177)] = 2333,
  [SMALL_STATE(178)] = 2340,
  [SMALL_STATE(179)] = 2347,
  [SMALL_STATE(180)] = 2354,
  [SMALL_STATE(181)] = 2361,
  [SMALL_STATE(182)] = 2368,
  [SMALL_STATE(183)] = 2375,
  [SMALL_STATE(184)] = 2382,
  [SMALL_STATE(185)] = 2389,
  [SMALL_STATE(186)] = 2396,
  [SMALL_STATE(187)] = 2403,
  [SMALL_STATE(188)] = 2410,
  [SMALL_STATE(189)] = 2417,
  [SMALL_STATE(190)] = 2424,
  [SMALL_STATE(191)] = 2431,
  [SMALL_STATE(192)] = 2438,
  [SMALL_STATE(193)] = 2445,
  [SMALL_STATE(194)] = 2452,
  [SMALL_STATE(195)] = 2459,
  [SMALL_STATE(196)] = 2466,
  [SMALL_STATE(197)] = 2473,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(189),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(188),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(185),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(179),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(165),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 7, 0, 10),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 3, 0, 7),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(197),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 11, 0, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 4, 0, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 10, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 10, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 4, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 9, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 9, 0, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 8, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 8, 0, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 5, 0, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 6, 0, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 6, 0, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(191),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(149),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat2, 2, 0, 0), SHIFT_REPEAT(177),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat2, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(156),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat3, 2, 0, 0), SHIFT_REPEAT(191),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat3, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(146),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_switchEnum_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_switchEnum_repeat1, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 7, 0, 9),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 6, 0, 9),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_block, 3, 0, 4),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 13, 0, 13),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 2, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminator, 1, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switch_case, 3, 0, 11),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 8, 0, 9),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goto, 2, 0, 5),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_decl, 4, 0, 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_block, 4, 0, 4),
  [329] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markers, 1, 0, 0),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(172),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_decl, 3, 0, 3),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 3, 0, 3),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 3),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 1, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 6),
  [365] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 8),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(190),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 8),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markers, 2, 0, 0),
  [403] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6, 0, 8),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(181),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(182),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(187),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [423] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(192),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(193),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [441] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 6, 0, 12),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(194),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(195),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(196),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_silica_mir(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
