#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 183
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 85
#define ALIAS_COUNT 0
#define TOKEN_COUNT 47
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 15

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  sym_number = 3,
  anon_sym_struct = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_COLON = 7,
  anon_sym_enum = 8,
  anon_sym_Copy = 9,
  anon_sym_Drop = 10,
  anon_sym_Move = 11,
  anon_sym_SEMI = 12,
  anon_sym_extern = 13,
  anon_sym_fn = 14,
  anon_sym_LPAREN = 15,
  anon_sym_COMMA = 16,
  anon_sym_RPAREN = 17,
  anon_sym_drop = 18,
  anon_sym_unborrow = 19,
  anon_sym_EQ = 20,
  anon_sym_call = 21,
  anon_sym_goto = 22,
  sym_return = 23,
  anon_sym_branch = 24,
  anon_sym_LBRACK = 25,
  anon_sym_true = 26,
  anon_sym_false = 27,
  anon_sym_RBRACK = 28,
  anon_sym_switchEnum = 29,
  sym_abort = 30,
  sym_unreachable = 31,
  anon_sym_DOT = 32,
  anon_sym_as = 33,
  anon_sym_STAR = 34,
  anon_sym_copy = 35,
  anon_sym_move = 36,
  anon_sym_unit = 37,
  anon_sym_AMP = 38,
  anon_sym_AMPmut = 39,
  anon_sym_AMPout = 40,
  anon_sym_AMPdrop = 41,
  anon_sym_AMPuninit = 42,
  anon_sym_COLON_COLON = 43,
  anon_sym_number = 44,
  anon_sym_boolean = 45,
  anon_sym_never = 46,
  sym_program = 47,
  sym_declaration = 48,
  sym_struct_decl = 49,
  sym_struct_field = 50,
  sym_enum_decl = 51,
  sym_enum_variant = 52,
  sym_markers = 53,
  sym_marker = 54,
  sym_param_decl = 55,
  sym_local_decl = 56,
  sym_function_decl = 57,
  sym_basic_block = 58,
  sym_statement = 59,
  sym_drop_stmt = 60,
  sym_unborrow_stmt = 61,
  sym_assignment = 62,
  sym_call = 63,
  sym_terminator = 64,
  sym_goto = 65,
  sym_branch = 66,
  sym_switchEnum = 67,
  sym_switch_case = 68,
  sym_place = 69,
  sym_operand = 70,
  sym_const = 71,
  sym_rvalue = 72,
  sym_type = 73,
  aux_sym_program_repeat1 = 74,
  aux_sym_struct_decl_repeat1 = 75,
  aux_sym_enum_decl_repeat1 = 76,
  aux_sym_markers_repeat1 = 77,
  aux_sym_function_decl_repeat1 = 78,
  aux_sym_function_decl_repeat2 = 79,
  aux_sym_function_decl_repeat3 = 80,
  aux_sym_basic_block_repeat1 = 81,
  aux_sym_call_repeat1 = 82,
  aux_sym_switchEnum_repeat1 = 83,
  aux_sym_type_repeat1 = 84,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_enum] = "enum",
  [anon_sym_Copy] = "Copy",
  [anon_sym_Drop] = "Drop",
  [anon_sym_Move] = "Move",
  [anon_sym_SEMI] = ";",
  [anon_sym_extern] = "extern",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_drop] = "drop",
  [anon_sym_unborrow] = "unborrow",
  [anon_sym_EQ] = "=",
  [anon_sym_call] = "call",
  [anon_sym_goto] = "goto",
  [sym_return] = "return",
  [anon_sym_branch] = "branch",
  [anon_sym_LBRACK] = "[",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_RBRACK] = "]",
  [anon_sym_switchEnum] = "switchEnum",
  [sym_abort] = "abort",
  [sym_unreachable] = "unreachable",
  [anon_sym_DOT] = ".",
  [anon_sym_as] = "as",
  [anon_sym_STAR] = "*",
  [anon_sym_copy] = "copy",
  [anon_sym_move] = "move",
  [anon_sym_unit] = "unit",
  [anon_sym_AMP] = "&",
  [anon_sym_AMPmut] = "&mut",
  [anon_sym_AMPout] = "&out",
  [anon_sym_AMPdrop] = "&drop",
  [anon_sym_AMPuninit] = "&uninit",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_number] = "number",
  [anon_sym_boolean] = "boolean",
  [anon_sym_never] = "never",
  [sym_program] = "program",
  [sym_declaration] = "declaration",
  [sym_struct_decl] = "struct_decl",
  [sym_struct_field] = "struct_field",
  [sym_enum_decl] = "enum_decl",
  [sym_enum_variant] = "enum_variant",
  [sym_markers] = "markers",
  [sym_marker] = "marker",
  [sym_param_decl] = "param_decl",
  [sym_local_decl] = "local_decl",
  [sym_function_decl] = "function_decl",
  [sym_basic_block] = "basic_block",
  [sym_statement] = "statement",
  [sym_drop_stmt] = "drop_stmt",
  [sym_unborrow_stmt] = "unborrow_stmt",
  [sym_assignment] = "assignment",
  [sym_call] = "call",
  [sym_terminator] = "terminator",
  [sym_goto] = "goto",
  [sym_branch] = "branch",
  [sym_switchEnum] = "switchEnum",
  [sym_switch_case] = "switch_case",
  [sym_place] = "place",
  [sym_operand] = "operand",
  [sym_const] = "const",
  [sym_rvalue] = "rvalue",
  [sym_type] = "type",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_struct_decl_repeat1] = "struct_decl_repeat1",
  [aux_sym_enum_decl_repeat1] = "enum_decl_repeat1",
  [aux_sym_markers_repeat1] = "markers_repeat1",
  [aux_sym_function_decl_repeat1] = "function_decl_repeat1",
  [aux_sym_function_decl_repeat2] = "function_decl_repeat2",
  [aux_sym_function_decl_repeat3] = "function_decl_repeat3",
  [aux_sym_basic_block_repeat1] = "basic_block_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_switchEnum_repeat1] = "switchEnum_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_Copy] = anon_sym_Copy,
  [anon_sym_Drop] = anon_sym_Drop,
  [anon_sym_Move] = anon_sym_Move,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_drop] = anon_sym_drop,
  [anon_sym_unborrow] = anon_sym_unborrow,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_goto] = anon_sym_goto,
  [sym_return] = sym_return,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_switchEnum] = anon_sym_switchEnum,
  [sym_abort] = sym_abort,
  [sym_unreachable] = sym_unreachable,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_copy] = anon_sym_copy,
  [anon_sym_move] = anon_sym_move,
  [anon_sym_unit] = anon_sym_unit,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_AMPmut] = anon_sym_AMPmut,
  [anon_sym_AMPout] = anon_sym_AMPout,
  [anon_sym_AMPdrop] = anon_sym_AMPdrop,
  [anon_sym_AMPuninit] = anon_sym_AMPuninit,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_never] = anon_sym_never,
  [sym_program] = sym_program,
  [sym_declaration] = sym_declaration,
  [sym_struct_decl] = sym_struct_decl,
  [sym_struct_field] = sym_struct_field,
  [sym_enum_decl] = sym_enum_decl,
  [sym_enum_variant] = sym_enum_variant,
  [sym_markers] = sym_markers,
  [sym_marker] = sym_marker,
  [sym_param_decl] = sym_param_decl,
  [sym_local_decl] = sym_local_decl,
  [sym_function_decl] = sym_function_decl,
  [sym_basic_block] = sym_basic_block,
  [sym_statement] = sym_statement,
  [sym_drop_stmt] = sym_drop_stmt,
  [sym_unborrow_stmt] = sym_unborrow_stmt,
  [sym_assignment] = sym_assignment,
  [sym_call] = sym_call,
  [sym_terminator] = sym_terminator,
  [sym_goto] = sym_goto,
  [sym_branch] = sym_branch,
  [sym_switchEnum] = sym_switchEnum,
  [sym_switch_case] = sym_switch_case,
  [sym_place] = sym_place,
  [sym_operand] = sym_operand,
  [sym_const] = sym_const,
  [sym_rvalue] = sym_rvalue,
  [sym_type] = sym_type,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_struct_decl_repeat1] = aux_sym_struct_decl_repeat1,
  [aux_sym_enum_decl_repeat1] = aux_sym_enum_decl_repeat1,
  [aux_sym_markers_repeat1] = aux_sym_markers_repeat1,
  [aux_sym_function_decl_repeat1] = aux_sym_function_decl_repeat1,
  [aux_sym_function_decl_repeat2] = aux_sym_function_decl_repeat2,
  [aux_sym_function_decl_repeat3] = aux_sym_function_decl_repeat3,
  [aux_sym_basic_block_repeat1] = aux_sym_basic_block_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_switchEnum_repeat1] = aux_sym_switchEnum_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Drop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Move] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_drop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unborrow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goto] = {
    .visible = true,
    .named = false,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_switchEnum] = {
    .visible = true,
    .named = false,
  },
  [sym_abort] = {
    .visible = true,
    .named = true,
  },
  [sym_unreachable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_move] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPmut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPdrop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPuninit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_never] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_markers] = {
    .visible = true,
    .named = true,
  },
  [sym_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_param_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_local_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_basic_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_drop_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_unborrow_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_terminator] = {
    .visible = true,
    .named = true,
  },
  [sym_goto] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_switchEnum] = {
    .visible = true,
    .named = true,
  },
  [sym_switch_case] = {
    .visible = true,
    .named = true,
  },
  [sym_place] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_rvalue] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_basic_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_switchEnum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_enum_name = 2,
  field_false_label = 3,
  field_field = 4,
  field_function = 5,
  field_label = 6,
  field_lhs = 7,
  field_name = 8,
  field_place = 9,
  field_rhs = 10,
  field_true_label = 11,
  field_type = 12,
  field_variant = 13,
  field_variant_name = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_enum_name] = "enum_name",
  [field_false_label] = "false_label",
  [field_field] = "field",
  [field_function] = "function",
  [field_label] = "label",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_place] = "place",
  [field_rhs] = "rhs",
  [field_true_label] = "true_label",
  [field_type] = "type",
  [field_variant] = "variant",
  [field_variant_name] = "variant_name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 11, .length = 1},
  [11] = {.index = 12, .length = 1},
  [12] = {.index = 13, .length = 2},
  [13] = {.index = 15, .length = 2},
  [14] = {.index = 17, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 2},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_label, 0},
  [5] =
    {field_place, 1},
  [6] =
    {field_label, 1},
  [7] =
    {field_lhs, 0},
    {field_rhs, 2},
  [9] =
    {field_field, 2},
  [10] =
    {field_variant, 2},
  [11] =
    {field_function, 1},
  [12] =
    {field_place, 2},
  [13] =
    {field_label, 2},
    {field_variant, 0},
  [15] =
    {field_enum_name, 0},
    {field_variant_name, 2},
  [17] =
    {field_condition, 2},
    {field_false_label, 11},
    {field_true_label, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '#', 17,
        '&', 33,
        '(', 25,
        ')', 27,
        '*', 32,
        ',', 26,
        '.', 31,
        ':', 23,
        ';', 24,
        '=', 28,
        '[', 29,
        ']', 30,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ';') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == ':') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'm') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMPmut);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_AMPout);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AMPdrop);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AMPuninit);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'D', 2,
        'M', 3,
        'a', 4,
        'b', 5,
        'c', 6,
        'd', 7,
        'e', 8,
        'f', 9,
        'g', 10,
        'm', 11,
        'n', 12,
        'r', 13,
        's', 14,
        't', 15,
        'u', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(20);
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(36);
      if (lookahead == 'w') ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'v') ADVANCE(53);
      END_STATE();
    case 33:
      if (lookahead == 'v') ADVANCE(54);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(55);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(57);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 39:
      if (lookahead == 'b') ADVANCE(60);
      if (lookahead == 'i') ADVANCE(61);
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 'y') ADVANCE(63);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 44:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 47:
      if (lookahead == 'y') ADVANCE(70);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 55:
      if (lookahead == 'b') ADVANCE(78);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(79);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(80);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(81);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Copy);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_Drop);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_Move);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 68:
      if (lookahead == 'c') ADVANCE(88);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_drop);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_goto);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_move);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(91);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 80:
      if (lookahead == 'c') ADVANCE(94);
      END_STATE();
    case 81:
      if (lookahead == 'c') ADVANCE(95);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 83:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_unit);
      END_STATE();
    case 85:
      if (lookahead == 'a') ADVANCE(97);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_abort);
      END_STATE();
    case 87:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 88:
      if (lookahead == 'h') ADVANCE(99);
      END_STATE();
    case 89:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_never);
      END_STATE();
    case 92:
      if (lookahead == 'r') ADVANCE(101);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(102);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 95:
      if (lookahead == 'h') ADVANCE(104);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(105);
      END_STATE();
    case 97:
      if (lookahead == 'c') ADVANCE(106);
      END_STATE();
    case 98:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_return);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 104:
      if (lookahead == 'E') ADVANCE(108);
      END_STATE();
    case 105:
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 106:
      if (lookahead == 'h') ADVANCE(110);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 108:
      if (lookahead == 'n') ADVANCE(111);
      END_STATE();
    case 109:
      if (lookahead == 'w') ADVANCE(112);
      END_STATE();
    case 110:
      if (lookahead == 'a') ADVANCE(113);
      END_STATE();
    case 111:
      if (lookahead == 'u') ADVANCE(114);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_unborrow);
      END_STATE();
    case 113:
      if (lookahead == 'b') ADVANCE(115);
      END_STATE();
    case 114:
      if (lookahead == 'm') ADVANCE(116);
      END_STATE();
    case 115:
      if (lookahead == 'l') ADVANCE(117);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_switchEnum);
      END_STATE();
    case 117:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_unreachable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 2},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 2},
  [162] = {.lex_state = 2},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 2},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 2},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 2},
  [174] = {.lex_state = 2},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 2},
  [180] = {.lex_state = 0},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_Copy] = ACTIONS(1),
    [anon_sym_Drop] = ACTIONS(1),
    [anon_sym_Move] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_drop] = ACTIONS(1),
    [anon_sym_unborrow] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_goto] = ACTIONS(1),
    [sym_return] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_switchEnum] = ACTIONS(1),
    [sym_abort] = ACTIONS(1),
    [sym_unreachable] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [anon_sym_move] = ACTIONS(1),
    [anon_sym_unit] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_AMPmut] = ACTIONS(1),
    [anon_sym_AMPout] = ACTIONS(1),
    [anon_sym_AMPdrop] = ACTIONS(1),
    [anon_sym_AMPuninit] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_never] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(152),
    [sym_declaration] = STATE(15),
    [sym_struct_decl] = STATE(56),
    [sym_enum_decl] = STATE(56),
    [sym_function_decl] = STATE(56),
    [aux_sym_program_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_struct] = ACTIONS(7),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_drop,
    ACTIONS(21), 1,
      anon_sym_unborrow,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_goto,
    ACTIONS(29), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      anon_sym_switchEnum,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(4), 1,
      aux_sym_basic_block_repeat1,
    STATE(100), 1,
      sym_place,
    STATE(109), 1,
      sym_terminator,
    STATE(139), 1,
      sym_statement,
    STATE(147), 1,
      sym_type,
    ACTIONS(27), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(120), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
    ACTIONS(35), 4,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    STATE(144), 4,
      sym_drop_stmt,
      sym_unborrow_stmt,
      sym_assignment,
      sym_call,
  [77] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_drop,
    ACTIONS(21), 1,
      anon_sym_unborrow,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_goto,
    ACTIONS(29), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      anon_sym_switchEnum,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym_basic_block_repeat1,
    STATE(100), 1,
      sym_place,
    STATE(109), 1,
      sym_terminator,
    STATE(139), 1,
      sym_statement,
    ACTIONS(27), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(120), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
    STATE(144), 4,
      sym_drop_stmt,
      sym_unborrow_stmt,
      sym_assignment,
      sym_call,
  [133] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_drop,
    ACTIONS(21), 1,
      anon_sym_unborrow,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_goto,
    ACTIONS(29), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      anon_sym_switchEnum,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(41), 1,
      sym_identifier,
    STATE(5), 1,
      aux_sym_basic_block_repeat1,
    STATE(100), 1,
      sym_place,
    STATE(108), 1,
      sym_terminator,
    STATE(139), 1,
      sym_statement,
    ACTIONS(27), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(120), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
    STATE(144), 4,
      sym_drop_stmt,
      sym_unborrow_stmt,
      sym_assignment,
      sym_call,
  [189] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_drop,
    ACTIONS(49), 1,
      anon_sym_unborrow,
    ACTIONS(52), 1,
      anon_sym_call,
    ACTIONS(57), 1,
      anon_sym_STAR,
    STATE(5), 1,
      aux_sym_basic_block_repeat1,
    STATE(100), 1,
      sym_place,
    STATE(139), 1,
      sym_statement,
    STATE(144), 4,
      sym_drop_stmt,
      sym_unborrow_stmt,
      sym_assignment,
      sym_call,
    ACTIONS(55), 6,
      anon_sym_goto,
      sym_return,
      anon_sym_branch,
      anon_sym_switchEnum,
      sym_abort,
      sym_unreachable,
  [231] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      sym_number,
    ACTIONS(68), 1,
      anon_sym_AMP,
    STATE(68), 1,
      sym_const,
    STATE(141), 1,
      sym_operand,
    STATE(142), 1,
      sym_rvalue,
    ACTIONS(66), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(64), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_unit,
    ACTIONS(70), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [268] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [297] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(47), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [323] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(122), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [349] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(107), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [375] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(116), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [401] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(118), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [427] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(37), 1,
      anon_sym_AMP,
    STATE(147), 1,
      sym_type,
    ACTIONS(39), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
    ACTIONS(35), 5,
      sym_identifier,
      anon_sym_unit,
      anon_sym_number,
      anon_sym_boolean,
      anon_sym_never,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_STAR,
    ACTIONS(55), 10,
      sym_identifier,
      anon_sym_drop,
      anon_sym_unborrow,
      anon_sym_call,
      anon_sym_goto,
      sym_return,
      anon_sym_branch,
      anon_sym_switchEnum,
      sym_abort,
      sym_unreachable,
  [472] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_struct,
    ACTIONS(9), 1,
      anon_sym_enum,
    ACTIONS(11), 1,
      anon_sym_extern,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    STATE(17), 2,
      sym_declaration,
      aux_sym_program_repeat1,
    STATE(56), 3,
      sym_struct_decl,
      sym_enum_decl,
      sym_function_decl,
  [500] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_number,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_const,
    STATE(92), 1,
      sym_operand,
    ACTIONS(66), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(64), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_unit,
  [526] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      anon_sym_struct,
    ACTIONS(85), 1,
      anon_sym_enum,
    ACTIONS(88), 1,
      anon_sym_extern,
    ACTIONS(91), 1,
      anon_sym_fn,
    STATE(17), 2,
      sym_declaration,
      aux_sym_program_repeat1,
    STATE(56), 3,
      sym_struct_decl,
      sym_enum_decl,
      sym_function_decl,
  [554] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_number,
    STATE(68), 1,
      sym_const,
    STATE(138), 1,
      sym_operand,
    ACTIONS(66), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(64), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_unit,
  [577] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_number,
    STATE(68), 1,
      sym_const,
    STATE(171), 1,
      sym_operand,
    ACTIONS(66), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(64), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_unit,
  [600] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_number,
    STATE(68), 1,
      sym_const,
    STATE(119), 1,
      sym_operand,
    ACTIONS(66), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(64), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_unit,
  [623] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_number,
    STATE(68), 1,
      sym_const,
    STATE(163), 1,
      sym_operand,
    ACTIONS(66), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(64), 4,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      anon_sym_unit,
  [646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [659] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(96), 5,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [676] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym_identifier,
    STATE(143), 1,
      sym_markers,
    STATE(31), 2,
      sym_marker,
      aux_sym_markers_repeat1,
    ACTIONS(104), 3,
      anon_sym_Copy,
      anon_sym_Drop,
      anon_sym_Move,
  [695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [708] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(136), 1,
      sym_markers,
    STATE(31), 2,
      sym_marker,
      aux_sym_markers_repeat1,
    ACTIONS(104), 3,
      anon_sym_Copy,
      anon_sym_Drop,
      anon_sym_Move,
  [727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [740] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(72), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(77), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [758] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      sym_identifier,
    STATE(29), 2,
      sym_marker,
      aux_sym_markers_repeat1,
    ACTIONS(118), 3,
      anon_sym_Copy,
      anon_sym_Drop,
      anon_sym_Move,
  [774] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(78), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [792] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(29), 2,
      sym_marker,
      aux_sym_markers_repeat1,
    ACTIONS(104), 3,
      anon_sym_Copy,
      anon_sym_Drop,
      anon_sym_Move,
  [808] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(36), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(72), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [826] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(77), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(78), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [844] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(33), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
    STATE(76), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [862] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(127), 4,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [878] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
    STATE(77), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [896] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [918] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [929] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [940] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1006] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1017] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1083] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1094] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1138] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1152] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_SEMI,
    ACTIONS(106), 3,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [1164] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(61), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1178] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(61), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1192] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1206] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 4,
      sym_identifier,
      anon_sym_Copy,
      anon_sym_Drop,
      anon_sym_Move,
  [1216] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(70), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1244] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    STATE(73), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 4,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 4,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    STATE(61), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1306] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1320] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(63), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1348] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1362] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_identifier,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    STATE(77), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat2,
  [1390] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(75), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat3,
  [1404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(95), 1,
      sym_place,
  [1417] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_function_decl_repeat1,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      aux_sym_switchEnum_repeat1,
  [1443] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      aux_sym_switchEnum_repeat1,
  [1456] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_function_decl_repeat1,
  [1469] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      aux_sym_switchEnum_repeat1,
  [1482] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_call_repeat1,
  [1495] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_identifier,
    ACTIONS(254), 1,
      anon_sym_RBRACK,
    STATE(84), 1,
      sym_switch_case,
  [1508] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      aux_sym_type_repeat1,
  [1521] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_call_repeat1,
  [1534] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(104), 1,
      sym_place,
  [1547] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(105), 1,
      sym_place,
  [1560] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(264), 1,
      anon_sym_SEMI,
  [1573] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_call_repeat1,
  [1586] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(106), 1,
      aux_sym_function_decl_repeat1,
  [1599] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(91), 1,
      sym_place,
  [1612] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
  [1625] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(23), 1,
      sym_place,
  [1638] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_type_repeat1,
  [1651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_STAR,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(35), 1,
      sym_place,
  [1664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      sym_param_decl,
  [1677] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(281), 1,
      anon_sym_EQ,
  [1690] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_type_repeat1,
  [1703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_param_decl,
  [1716] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_function_decl_repeat1,
  [1729] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(289), 1,
      anon_sym_SEMI,
  [1742] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_DOT,
    ACTIONS(100), 1,
      anon_sym_as,
    ACTIONS(291), 1,
      anon_sym_SEMI,
  [1755] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_function_decl_repeat1,
  [1768] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1792] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1808] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1832] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(112), 1,
      sym_switch_case,
  [1842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    ACTIONS(319), 1,
      anon_sym_COLON_COLON,
  [1908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1916] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_identifier,
    STATE(124), 1,
      sym_param_decl,
  [1926] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_LPAREN,
  [1941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [1948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_LBRACE,
  [1955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
  [1962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      sym_identifier,
  [1969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_LBRACE,
  [1976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
  [1983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_LPAREN,
  [1990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      sym_identifier,
  [1997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_identifier,
  [2004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_LBRACE,
  [2011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
  [2018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_SEMI,
  [2025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_LPAREN,
  [2032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_SEMI,
  [2039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_SEMI,
  [2046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym_identifier,
  [2053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_SEMI,
  [2060] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [2067] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [2074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_SEMI,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_LBRACK,
  [2088] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      anon_sym_LBRACK,
  [2095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      sym_identifier,
  [2102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      sym_identifier,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      ts_builtin_sym_end,
  [2116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_SEMI,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      anon_sym_LPAREN,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_true,
  [2137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_LBRACE,
  [2144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_LPAREN,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      anon_sym_LPAREN,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_SEMI,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      anon_sym_fn,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_COLON,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_COLON,
  [2186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_LPAREN,
  [2193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_COLON,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      sym_identifier,
  [2207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      sym_identifier,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      sym_identifier,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_COLON,
  [2228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_SEMI,
  [2235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_SEMI,
  [2242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      anon_sym_RPAREN,
  [2249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_COMMA,
  [2256] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      anon_sym_COLON,
  [2263] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      anon_sym_COLON,
  [2270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(419), 1,
      anon_sym_SEMI,
  [2277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(421), 1,
      anon_sym_LBRACE,
  [2284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(423), 1,
      anon_sym_SEMI,
  [2291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(425), 1,
      anon_sym_false,
  [2298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(427), 1,
      anon_sym_COLON,
  [2305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(429), 1,
      sym_identifier,
  [2312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(431), 1,
      anon_sym_RBRACK,
  [2319] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(433), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 77,
  [SMALL_STATE(4)] = 133,
  [SMALL_STATE(5)] = 189,
  [SMALL_STATE(6)] = 231,
  [SMALL_STATE(7)] = 268,
  [SMALL_STATE(8)] = 297,
  [SMALL_STATE(9)] = 323,
  [SMALL_STATE(10)] = 349,
  [SMALL_STATE(11)] = 375,
  [SMALL_STATE(12)] = 401,
  [SMALL_STATE(13)] = 427,
  [SMALL_STATE(14)] = 453,
  [SMALL_STATE(15)] = 472,
  [SMALL_STATE(16)] = 500,
  [SMALL_STATE(17)] = 526,
  [SMALL_STATE(18)] = 554,
  [SMALL_STATE(19)] = 577,
  [SMALL_STATE(20)] = 600,
  [SMALL_STATE(21)] = 623,
  [SMALL_STATE(22)] = 646,
  [SMALL_STATE(23)] = 659,
  [SMALL_STATE(24)] = 676,
  [SMALL_STATE(25)] = 695,
  [SMALL_STATE(26)] = 708,
  [SMALL_STATE(27)] = 727,
  [SMALL_STATE(28)] = 740,
  [SMALL_STATE(29)] = 758,
  [SMALL_STATE(30)] = 774,
  [SMALL_STATE(31)] = 792,
  [SMALL_STATE(32)] = 808,
  [SMALL_STATE(33)] = 826,
  [SMALL_STATE(34)] = 844,
  [SMALL_STATE(35)] = 862,
  [SMALL_STATE(36)] = 878,
  [SMALL_STATE(37)] = 896,
  [SMALL_STATE(38)] = 907,
  [SMALL_STATE(39)] = 918,
  [SMALL_STATE(40)] = 929,
  [SMALL_STATE(41)] = 940,
  [SMALL_STATE(42)] = 951,
  [SMALL_STATE(43)] = 962,
  [SMALL_STATE(44)] = 973,
  [SMALL_STATE(45)] = 984,
  [SMALL_STATE(46)] = 995,
  [SMALL_STATE(47)] = 1006,
  [SMALL_STATE(48)] = 1017,
  [SMALL_STATE(49)] = 1028,
  [SMALL_STATE(50)] = 1039,
  [SMALL_STATE(51)] = 1050,
  [SMALL_STATE(52)] = 1061,
  [SMALL_STATE(53)] = 1072,
  [SMALL_STATE(54)] = 1083,
  [SMALL_STATE(55)] = 1094,
  [SMALL_STATE(56)] = 1105,
  [SMALL_STATE(57)] = 1116,
  [SMALL_STATE(58)] = 1127,
  [SMALL_STATE(59)] = 1138,
  [SMALL_STATE(60)] = 1152,
  [SMALL_STATE(61)] = 1164,
  [SMALL_STATE(62)] = 1178,
  [SMALL_STATE(63)] = 1192,
  [SMALL_STATE(64)] = 1206,
  [SMALL_STATE(65)] = 1216,
  [SMALL_STATE(66)] = 1230,
  [SMALL_STATE(67)] = 1244,
  [SMALL_STATE(68)] = 1258,
  [SMALL_STATE(69)] = 1268,
  [SMALL_STATE(70)] = 1278,
  [SMALL_STATE(71)] = 1292,
  [SMALL_STATE(72)] = 1306,
  [SMALL_STATE(73)] = 1320,
  [SMALL_STATE(74)] = 1334,
  [SMALL_STATE(75)] = 1348,
  [SMALL_STATE(76)] = 1362,
  [SMALL_STATE(77)] = 1376,
  [SMALL_STATE(78)] = 1390,
  [SMALL_STATE(79)] = 1404,
  [SMALL_STATE(80)] = 1417,
  [SMALL_STATE(81)] = 1430,
  [SMALL_STATE(82)] = 1443,
  [SMALL_STATE(83)] = 1456,
  [SMALL_STATE(84)] = 1469,
  [SMALL_STATE(85)] = 1482,
  [SMALL_STATE(86)] = 1495,
  [SMALL_STATE(87)] = 1508,
  [SMALL_STATE(88)] = 1521,
  [SMALL_STATE(89)] = 1534,
  [SMALL_STATE(90)] = 1547,
  [SMALL_STATE(91)] = 1560,
  [SMALL_STATE(92)] = 1573,
  [SMALL_STATE(93)] = 1586,
  [SMALL_STATE(94)] = 1599,
  [SMALL_STATE(95)] = 1612,
  [SMALL_STATE(96)] = 1625,
  [SMALL_STATE(97)] = 1638,
  [SMALL_STATE(98)] = 1651,
  [SMALL_STATE(99)] = 1664,
  [SMALL_STATE(100)] = 1677,
  [SMALL_STATE(101)] = 1690,
  [SMALL_STATE(102)] = 1703,
  [SMALL_STATE(103)] = 1716,
  [SMALL_STATE(104)] = 1729,
  [SMALL_STATE(105)] = 1742,
  [SMALL_STATE(106)] = 1755,
  [SMALL_STATE(107)] = 1768,
  [SMALL_STATE(108)] = 1776,
  [SMALL_STATE(109)] = 1784,
  [SMALL_STATE(110)] = 1792,
  [SMALL_STATE(111)] = 1800,
  [SMALL_STATE(112)] = 1808,
  [SMALL_STATE(113)] = 1816,
  [SMALL_STATE(114)] = 1824,
  [SMALL_STATE(115)] = 1832,
  [SMALL_STATE(116)] = 1842,
  [SMALL_STATE(117)] = 1850,
  [SMALL_STATE(118)] = 1858,
  [SMALL_STATE(119)] = 1866,
  [SMALL_STATE(120)] = 1874,
  [SMALL_STATE(121)] = 1882,
  [SMALL_STATE(122)] = 1890,
  [SMALL_STATE(123)] = 1898,
  [SMALL_STATE(124)] = 1908,
  [SMALL_STATE(125)] = 1916,
  [SMALL_STATE(126)] = 1926,
  [SMALL_STATE(127)] = 1934,
  [SMALL_STATE(128)] = 1941,
  [SMALL_STATE(129)] = 1948,
  [SMALL_STATE(130)] = 1955,
  [SMALL_STATE(131)] = 1962,
  [SMALL_STATE(132)] = 1969,
  [SMALL_STATE(133)] = 1976,
  [SMALL_STATE(134)] = 1983,
  [SMALL_STATE(135)] = 1990,
  [SMALL_STATE(136)] = 1997,
  [SMALL_STATE(137)] = 2004,
  [SMALL_STATE(138)] = 2011,
  [SMALL_STATE(139)] = 2018,
  [SMALL_STATE(140)] = 2025,
  [SMALL_STATE(141)] = 2032,
  [SMALL_STATE(142)] = 2039,
  [SMALL_STATE(143)] = 2046,
  [SMALL_STATE(144)] = 2053,
  [SMALL_STATE(145)] = 2060,
  [SMALL_STATE(146)] = 2067,
  [SMALL_STATE(147)] = 2074,
  [SMALL_STATE(148)] = 2081,
  [SMALL_STATE(149)] = 2088,
  [SMALL_STATE(150)] = 2095,
  [SMALL_STATE(151)] = 2102,
  [SMALL_STATE(152)] = 2109,
  [SMALL_STATE(153)] = 2116,
  [SMALL_STATE(154)] = 2123,
  [SMALL_STATE(155)] = 2130,
  [SMALL_STATE(156)] = 2137,
  [SMALL_STATE(157)] = 2144,
  [SMALL_STATE(158)] = 2151,
  [SMALL_STATE(159)] = 2158,
  [SMALL_STATE(160)] = 2165,
  [SMALL_STATE(161)] = 2172,
  [SMALL_STATE(162)] = 2179,
  [SMALL_STATE(163)] = 2186,
  [SMALL_STATE(164)] = 2193,
  [SMALL_STATE(165)] = 2200,
  [SMALL_STATE(166)] = 2207,
  [SMALL_STATE(167)] = 2214,
  [SMALL_STATE(168)] = 2221,
  [SMALL_STATE(169)] = 2228,
  [SMALL_STATE(170)] = 2235,
  [SMALL_STATE(171)] = 2242,
  [SMALL_STATE(172)] = 2249,
  [SMALL_STATE(173)] = 2256,
  [SMALL_STATE(174)] = 2263,
  [SMALL_STATE(175)] = 2270,
  [SMALL_STATE(176)] = 2277,
  [SMALL_STATE(177)] = 2284,
  [SMALL_STATE(178)] = 2291,
  [SMALL_STATE(179)] = 2298,
  [SMALL_STATE(180)] = 2305,
  [SMALL_STATE(181)] = 2312,
  [SMALL_STATE(182)] = 2319,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(158),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(160),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(165),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 3, 0, 9),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 3, 0, 8),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(174),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markers_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markers_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markers, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 6, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 9, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 4, 0, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 8, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 4, 0, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 10, 0, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 8, 0, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 6, 0, 2),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(173),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(168),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_marker, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat3, 2, 0, 0), SHIFT_REPEAT(164),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat3, 2, 0, 0),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat2, 2, 0, 0), SHIFT_REPEAT(182),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat2, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(176),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_switchEnum_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_switchEnum_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_drop_stmt, 2, 0, 5),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unborrow_stmt, 2, 0, 5),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_decl, 3, 0, 3),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_block, 4, 0, 4),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_block, 3, 0, 4),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 13, 0, 14),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 8, 0, 11),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switch_case, 3, 0, 12),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 7, 0, 11),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 3, 0, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 6, 0, 11),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 3),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminator, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goto, 2, 0, 6),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_decl, 4, 0, 3),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 1, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 7),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 10),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [373] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 10),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6, 0, 10),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [423] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 6, 0, 13),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(180),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(181),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_silica_mir(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
