#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 184
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 78
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 14

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  sym_number = 3,
  anon_sym_struct = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_COLON = 7,
  anon_sym_enum = 8,
  anon_sym_Copy = 9,
  anon_sym_Drop = 10,
  anon_sym_extern = 11,
  anon_sym_fn = 12,
  anon_sym_LPAREN = 13,
  anon_sym_COMMA = 14,
  anon_sym_RPAREN = 15,
  anon_sym_SEMI = 16,
  anon_sym_EQ = 17,
  anon_sym_call = 18,
  anon_sym_goto = 19,
  sym_return = 20,
  anon_sym_branch = 21,
  anon_sym_LBRACK = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  anon_sym_RBRACK = 25,
  anon_sym_switchEnum = 26,
  sym_abort = 27,
  sym_unreachable = 28,
  anon_sym_DOT = 29,
  anon_sym_as = 30,
  anon_sym_payload = 31,
  anon_sym_STAR = 32,
  anon_sym_copy = 33,
  anon_sym_move = 34,
  anon_sym_AMP = 35,
  anon_sym_AMPmut = 36,
  anon_sym_AMPout = 37,
  anon_sym_AMPdrop = 38,
  anon_sym_AMPuninit = 39,
  anon_sym_COLON_COLON = 40,
  anon_sym_number = 41,
  anon_sym_boolean = 42,
  sym_program = 43,
  sym_declaration = 44,
  sym_struct_decl = 45,
  sym_struct_field = 46,
  sym_enum_decl = 47,
  sym_enum_variant = 48,
  sym_markers = 49,
  sym_extern_fn = 50,
  sym_param_decl = 51,
  sym_local_decl = 52,
  sym_function_decl = 53,
  sym_basic_block = 54,
  sym_statement = 55,
  sym_assignment = 56,
  sym_call = 57,
  sym_terminator = 58,
  sym_goto = 59,
  sym_branch = 60,
  sym_switchEnum = 61,
  sym_switch_case = 62,
  sym_place = 63,
  sym_operand = 64,
  sym_const = 65,
  sym_rvalue = 66,
  sym_type = 67,
  aux_sym_program_repeat1 = 68,
  aux_sym_struct_decl_repeat1 = 69,
  aux_sym_enum_decl_repeat1 = 70,
  aux_sym_extern_fn_repeat1 = 71,
  aux_sym_function_decl_repeat1 = 72,
  aux_sym_function_decl_repeat2 = 73,
  aux_sym_basic_block_repeat1 = 74,
  aux_sym_call_repeat1 = 75,
  aux_sym_switchEnum_repeat1 = 76,
  aux_sym_type_repeat1 = 77,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_enum] = "enum",
  [anon_sym_Copy] = "Copy",
  [anon_sym_Drop] = "Drop",
  [anon_sym_extern] = "extern",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_call] = "call",
  [anon_sym_goto] = "goto",
  [sym_return] = "return",
  [anon_sym_branch] = "branch",
  [anon_sym_LBRACK] = "[",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_RBRACK] = "]",
  [anon_sym_switchEnum] = "switchEnum",
  [sym_abort] = "abort",
  [sym_unreachable] = "unreachable",
  [anon_sym_DOT] = ".",
  [anon_sym_as] = "as",
  [anon_sym_payload] = "payload",
  [anon_sym_STAR] = "*",
  [anon_sym_copy] = "copy",
  [anon_sym_move] = "move",
  [anon_sym_AMP] = "&",
  [anon_sym_AMPmut] = "&mut",
  [anon_sym_AMPout] = "&out",
  [anon_sym_AMPdrop] = "&drop",
  [anon_sym_AMPuninit] = "&uninit",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_number] = "number",
  [anon_sym_boolean] = "boolean",
  [sym_program] = "program",
  [sym_declaration] = "declaration",
  [sym_struct_decl] = "struct_decl",
  [sym_struct_field] = "struct_field",
  [sym_enum_decl] = "enum_decl",
  [sym_enum_variant] = "enum_variant",
  [sym_markers] = "markers",
  [sym_extern_fn] = "extern_fn",
  [sym_param_decl] = "param_decl",
  [sym_local_decl] = "local_decl",
  [sym_function_decl] = "function_decl",
  [sym_basic_block] = "basic_block",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_call] = "call",
  [sym_terminator] = "terminator",
  [sym_goto] = "goto",
  [sym_branch] = "branch",
  [sym_switchEnum] = "switchEnum",
  [sym_switch_case] = "switch_case",
  [sym_place] = "place",
  [sym_operand] = "operand",
  [sym_const] = "const",
  [sym_rvalue] = "rvalue",
  [sym_type] = "type",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_struct_decl_repeat1] = "struct_decl_repeat1",
  [aux_sym_enum_decl_repeat1] = "enum_decl_repeat1",
  [aux_sym_extern_fn_repeat1] = "extern_fn_repeat1",
  [aux_sym_function_decl_repeat1] = "function_decl_repeat1",
  [aux_sym_function_decl_repeat2] = "function_decl_repeat2",
  [aux_sym_basic_block_repeat1] = "basic_block_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_switchEnum_repeat1] = "switchEnum_repeat1",
  [aux_sym_type_repeat1] = "type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_Copy] = anon_sym_Copy,
  [anon_sym_Drop] = anon_sym_Drop,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_goto] = anon_sym_goto,
  [sym_return] = sym_return,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_switchEnum] = anon_sym_switchEnum,
  [sym_abort] = sym_abort,
  [sym_unreachable] = sym_unreachable,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_payload] = anon_sym_payload,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_copy] = anon_sym_copy,
  [anon_sym_move] = anon_sym_move,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_AMPmut] = anon_sym_AMPmut,
  [anon_sym_AMPout] = anon_sym_AMPout,
  [anon_sym_AMPdrop] = anon_sym_AMPdrop,
  [anon_sym_AMPuninit] = anon_sym_AMPuninit,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_boolean] = anon_sym_boolean,
  [sym_program] = sym_program,
  [sym_declaration] = sym_declaration,
  [sym_struct_decl] = sym_struct_decl,
  [sym_struct_field] = sym_struct_field,
  [sym_enum_decl] = sym_enum_decl,
  [sym_enum_variant] = sym_enum_variant,
  [sym_markers] = sym_markers,
  [sym_extern_fn] = sym_extern_fn,
  [sym_param_decl] = sym_param_decl,
  [sym_local_decl] = sym_local_decl,
  [sym_function_decl] = sym_function_decl,
  [sym_basic_block] = sym_basic_block,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_call] = sym_call,
  [sym_terminator] = sym_terminator,
  [sym_goto] = sym_goto,
  [sym_branch] = sym_branch,
  [sym_switchEnum] = sym_switchEnum,
  [sym_switch_case] = sym_switch_case,
  [sym_place] = sym_place,
  [sym_operand] = sym_operand,
  [sym_const] = sym_const,
  [sym_rvalue] = sym_rvalue,
  [sym_type] = sym_type,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_struct_decl_repeat1] = aux_sym_struct_decl_repeat1,
  [aux_sym_enum_decl_repeat1] = aux_sym_enum_decl_repeat1,
  [aux_sym_extern_fn_repeat1] = aux_sym_extern_fn_repeat1,
  [aux_sym_function_decl_repeat1] = aux_sym_function_decl_repeat1,
  [aux_sym_function_decl_repeat2] = aux_sym_function_decl_repeat2,
  [aux_sym_basic_block_repeat1] = aux_sym_basic_block_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_switchEnum_repeat1] = aux_sym_switchEnum_repeat1,
  [aux_sym_type_repeat1] = aux_sym_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Drop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goto] = {
    .visible = true,
    .named = false,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_switchEnum] = {
    .visible = true,
    .named = false,
  },
  [sym_abort] = {
    .visible = true,
    .named = true,
  },
  [sym_unreachable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_payload] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_copy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_move] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPmut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPdrop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPuninit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_markers] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_param_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_local_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_basic_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_terminator] = {
    .visible = true,
    .named = true,
  },
  [sym_goto] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_switchEnum] = {
    .visible = true,
    .named = true,
  },
  [sym_switch_case] = {
    .visible = true,
    .named = true,
  },
  [sym_place] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_rvalue] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extern_fn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_basic_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_switchEnum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_enum_name = 2,
  field_false_label = 3,
  field_field = 4,
  field_function = 5,
  field_label = 6,
  field_lhs = 7,
  field_name = 8,
  field_place = 9,
  field_rhs = 10,
  field_true_label = 11,
  field_type = 12,
  field_variant = 13,
  field_variant_name = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_enum_name] = "enum_name",
  [field_false_label] = "false_label",
  [field_field] = "field",
  [field_function] = "function",
  [field_label] = "label",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_place] = "place",
  [field_rhs] = "rhs",
  [field_true_label] = "true_label",
  [field_type] = "type",
  [field_variant] = "variant",
  [field_variant_name] = "variant_name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 11, .length = 1},
  [11] = {.index = 12, .length = 2},
  [12] = {.index = 14, .length = 2},
  [13] = {.index = 16, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 2},
  [2] =
    {field_name, 0},
    {field_type, 2},
  [4] =
    {field_label, 0},
  [5] =
    {field_label, 1},
  [6] =
    {field_lhs, 0},
    {field_rhs, 2},
  [8] =
    {field_field, 2},
  [9] =
    {field_function, 1},
  [10] =
    {field_place, 2},
  [11] =
    {field_variant, 3},
  [12] =
    {field_label, 2},
    {field_variant, 0},
  [14] =
    {field_enum_name, 0},
    {field_variant_name, 2},
  [16] =
    {field_condition, 2},
    {field_false_label, 11},
    {field_true_label, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 172,
  [173] = 173,
  [174] = 174,
  [175] = 175,
  [176] = 176,
  [177] = 177,
  [178] = 178,
  [179] = 179,
  [180] = 180,
  [181] = 181,
  [182] = 182,
  [183] = 183,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '#', 17,
        '&', 33,
        '(', 24,
        ')', 26,
        '*', 32,
        ',', 25,
        '.', 31,
        ':', 23,
        ';', 27,
        '=', 28,
        '[', 29,
        ']', 30,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ';') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == ':') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'm') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMPmut);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_AMPout);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AMPdrop);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AMPuninit);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'C', 1,
        'D', 2,
        'a', 3,
        'b', 4,
        'c', 5,
        'e', 6,
        'f', 7,
        'g', 8,
        'm', 9,
        'n', 10,
        'p', 11,
        'r', 12,
        's', 13,
        't', 14,
        'u', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'b') ADVANCE(18);
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'w') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'v') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 31:
      if (lookahead == 'y') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(56);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 43:
      if (lookahead == 'y') ADVANCE(62);
      END_STATE();
    case 44:
      if (lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(66);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 49:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(71);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_Copy);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_Drop);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 60:
      if (lookahead == 'c') ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_copy);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_goto);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_move);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 71:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 72:
      if (lookahead == 'c') ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_abort);
      END_STATE();
    case 76:
      if (lookahead == 'a') ADVANCE(86);
      END_STATE();
    case 77:
      if (lookahead == 'h') ADVANCE(87);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(90);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 84:
      if (lookahead == 'h') ADVANCE(93);
      END_STATE();
    case 85:
      if (lookahead == 'c') ADVANCE(94);
      END_STATE();
    case 86:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_number);
      END_STATE();
    case 90:
      if (lookahead == 'd') ADVANCE(96);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_return);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 93:
      if (lookahead == 'E') ADVANCE(97);
      END_STATE();
    case 94:
      if (lookahead == 'h') ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_payload);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 98:
      if (lookahead == 'a') ADVANCE(100);
      END_STATE();
    case 99:
      if (lookahead == 'u') ADVANCE(101);
      END_STATE();
    case 100:
      if (lookahead == 'b') ADVANCE(102);
      END_STATE();
    case 101:
      if (lookahead == 'm') ADVANCE(103);
      END_STATE();
    case 102:
      if (lookahead == 'l') ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_switchEnum);
      END_STATE();
    case 104:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_unreachable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 2},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 2},
  [162] = {.lex_state = 2},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 2},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 0},
  [176] = {.lex_state = 0},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0},
  [179] = {.lex_state = 0},
  [180] = {.lex_state = 2},
  [181] = {.lex_state = 0},
  [182] = {.lex_state = 0},
  [183] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_Copy] = ACTIONS(1),
    [anon_sym_Drop] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_goto] = ACTIONS(1),
    [sym_return] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_switchEnum] = ACTIONS(1),
    [sym_abort] = ACTIONS(1),
    [sym_unreachable] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_payload] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_copy] = ACTIONS(1),
    [anon_sym_move] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_AMPmut] = ACTIONS(1),
    [anon_sym_AMPout] = ACTIONS(1),
    [anon_sym_AMPdrop] = ACTIONS(1),
    [anon_sym_AMPuninit] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(171),
    [sym_declaration] = STATE(8),
    [sym_struct_decl] = STATE(35),
    [sym_enum_decl] = STATE(35),
    [sym_extern_fn] = STATE(35),
    [sym_function_decl] = STATE(35),
    [aux_sym_program_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_struct] = ACTIONS(7),
    [anon_sym_enum] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(11),
    [anon_sym_fn] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_call,
    ACTIONS(23), 1,
      anon_sym_goto,
    ACTIONS(27), 1,
      anon_sym_branch,
    ACTIONS(29), 1,
      anon_sym_switchEnum,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(4), 1,
      aux_sym_basic_block_repeat1,
    STATE(108), 1,
      sym_terminator,
    STATE(122), 1,
      sym_place,
    STATE(149), 1,
      sym_type,
    STATE(170), 1,
      sym_statement,
    ACTIONS(37), 2,
      anon_sym_number,
      anon_sym_boolean,
    STATE(169), 2,
      sym_assignment,
      sym_call,
    ACTIONS(25), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(101), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [70] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_call,
    ACTIONS(23), 1,
      anon_sym_goto,
    ACTIONS(27), 1,
      anon_sym_branch,
    ACTIONS(29), 1,
      anon_sym_switchEnum,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym_basic_block_repeat1,
    STATE(108), 1,
      sym_terminator,
    STATE(122), 1,
      sym_place,
    STATE(170), 1,
      sym_statement,
    STATE(169), 2,
      sym_assignment,
      sym_call,
    ACTIONS(25), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(101), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
  [121] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_call,
    ACTIONS(23), 1,
      anon_sym_goto,
    ACTIONS(27), 1,
      anon_sym_branch,
    ACTIONS(29), 1,
      anon_sym_switchEnum,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(5), 1,
      aux_sym_basic_block_repeat1,
    STATE(99), 1,
      sym_terminator,
    STATE(122), 1,
      sym_place,
    STATE(170), 1,
      sym_statement,
    STATE(169), 2,
      sym_assignment,
      sym_call,
    ACTIONS(25), 3,
      sym_return,
      sym_abort,
      sym_unreachable,
    STATE(101), 3,
      sym_goto,
      sym_branch,
      sym_switchEnum,
  [172] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_call,
    ACTIONS(52), 1,
      anon_sym_STAR,
    STATE(5), 1,
      aux_sym_basic_block_repeat1,
    STATE(122), 1,
      sym_place,
    STATE(170), 1,
      sym_statement,
    STATE(169), 2,
      sym_assignment,
      sym_call,
    ACTIONS(50), 6,
      anon_sym_goto,
      sym_return,
      anon_sym_branch,
      anon_sym_switchEnum,
      sym_abort,
      sym_unreachable,
  [209] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(63), 1,
      anon_sym_AMP,
    STATE(65), 1,
      sym_const,
    STATE(140), 1,
      sym_operand,
    STATE(141), 1,
      sym_rvalue,
    ACTIONS(59), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(65), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [245] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      anon_sym_struct,
    ACTIONS(72), 1,
      anon_sym_enum,
    ACTIONS(75), 1,
      anon_sym_extern,
    ACTIONS(78), 1,
      anon_sym_fn,
    STATE(7), 2,
      sym_declaration,
      aux_sym_program_repeat1,
    STATE(35), 4,
      sym_struct_decl,
      sym_enum_decl,
      sym_extern_fn,
      sym_function_decl,
  [274] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_struct,
    ACTIONS(9), 1,
      anon_sym_enum,
    ACTIONS(11), 1,
      anon_sym_extern,
    ACTIONS(13), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym_declaration,
      aux_sym_program_repeat1,
    STATE(35), 4,
      sym_struct_decl,
      sym_enum_decl,
      sym_extern_fn,
      sym_function_decl,
  [303] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 2,
      anon_sym_LPAREN,
      anon_sym_STAR,
    ACTIONS(50), 8,
      sym_identifier,
      anon_sym_call,
      anon_sym_goto,
      sym_return,
      anon_sym_branch,
      anon_sym_switchEnum,
      sym_abort,
      sym_unreachable,
  [348] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(121), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [372] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(118), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [396] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(114), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [420] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(149), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [444] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(43), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [468] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_AMP,
    STATE(120), 1,
      sym_type,
    ACTIONS(37), 3,
      sym_identifier,
      anon_sym_number,
      anon_sym_boolean,
    ACTIONS(35), 4,
      anon_sym_AMPmut,
      anon_sym_AMPout,
      anon_sym_AMPdrop,
      anon_sym_AMPuninit,
  [492] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_const,
    STATE(80), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [517] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(65), 1,
      sym_const,
    STATE(153), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [539] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(65), 1,
      sym_const,
    STATE(112), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [561] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(65), 1,
      sym_const,
    STATE(172), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [583] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_number,
    STATE(65), 1,
      sym_const,
    STATE(137), 1,
      sym_operand,
    ACTIONS(61), 2,
      anon_sym_copy,
      anon_sym_move,
    ACTIONS(59), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 7,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(91), 6,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_as,
  [633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 7,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 7,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_as,
  [659] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
    STATE(78), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
  [677] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
    STATE(59), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [695] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(72), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
    STATE(78), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
  [713] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(78), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
    STATE(79), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [731] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(29), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
    STATE(56), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [749] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
    STATE(79), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [767] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [778] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [811] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [844] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [877] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [943] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [954] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [976] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(147), 4,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [989] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_extern,
      anon_sym_fn,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 5,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1022] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(64), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1036] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [1050] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(163), 1,
      anon_sym_Copy,
    ACTIONS(165), 1,
      anon_sym_Drop,
    STATE(125), 1,
      sym_markers,
  [1066] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    STATE(75), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1080] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [1094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(77), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    STATE(73), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1122] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(117), 1,
      sym_place,
  [1138] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(23), 1,
      sym_place,
  [1154] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    STATE(74), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 4,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1178] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(111), 1,
      sym_place,
  [1194] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(113), 1,
      sym_place,
  [1210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_identifier,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [1224] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(51), 1,
      sym_place,
  [1240] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(60), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 4,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1264] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_identifier,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [1278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    STATE(74), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    STATE(74), 2,
      sym_enum_variant,
      aux_sym_enum_decl_repeat1,
  [1306] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(77), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1320] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_Copy,
    ACTIONS(165), 1,
      anon_sym_Drop,
    ACTIONS(201), 1,
      sym_identifier,
    STATE(160), 1,
      sym_markers,
  [1336] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(77), 2,
      sym_struct_field,
      aux_sym_struct_decl_repeat1,
  [1350] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_identifier,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(78), 2,
      sym_local_decl,
      aux_sym_function_decl_repeat1,
  [1364] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(68), 2,
      sym_basic_block,
      aux_sym_function_decl_repeat2,
  [1378] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_call_repeat1,
  [1391] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_type_repeat1,
  [1404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_call_repeat1,
  [1417] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      sym_switch_case,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_call_repeat1,
  [1443] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_extern_fn_repeat1,
  [1456] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_type_repeat1,
  [1469] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_type_repeat1,
  [1482] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_SEMI,
    ACTIONS(97), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1493] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_extern_fn_repeat1,
  [1506] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    STATE(94), 1,
      aux_sym_switchEnum_repeat1,
  [1519] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_extern_fn_repeat1,
  [1532] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      sym_param_decl,
  [1545] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_extern_fn_repeat1,
  [1558] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
    STATE(96), 1,
      aux_sym_switchEnum_repeat1,
  [1571] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      sym_param_decl,
  [1584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RBRACK,
    STATE(96), 1,
      aux_sym_switchEnum_repeat1,
  [1597] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_extern_fn_repeat1,
  [1610] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_SEMI,
    ACTIONS(271), 1,
      anon_sym_COLON_COLON,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1676] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    STATE(103), 1,
      sym_switch_case,
  [1686] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(287), 1,
      anon_sym_Drop,
  [1696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1704] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(287), 1,
      anon_sym_Copy,
  [1714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1722] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(293), 1,
      anon_sym_as,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1740] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(295), 1,
      anon_sym_SEMI,
  [1750] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
  [1784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    STATE(115), 1,
      sym_param_decl,
  [1802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1818] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_DOT,
    ACTIONS(307), 1,
      anon_sym_EQ,
  [1828] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1836] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
  [1843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym_identifier,
  [1850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_COLON,
  [1857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_SEMI,
  [1864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_identifier,
  [1871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_LPAREN,
  [1878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_LBRACE,
  [1885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_SEMI,
  [1892] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_LBRACE,
  [1899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COLON,
  [1906] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      sym_identifier,
  [1913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COLON,
  [1920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_COLON,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_RPAREN,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_LPAREN,
  [1941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_LBRACE,
  [1948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_SEMI,
  [1955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_SEMI,
  [1962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      sym_identifier,
  [1969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RPAREN,
  [1976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_SEMI,
  [1983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_LPAREN,
  [1990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_LBRACK,
  [1997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_LBRACK,
  [2004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      sym_identifier,
  [2011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [2018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_DOT,
  [2025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      sym_identifier,
  [2032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      anon_sym_SEMI,
  [2039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_LPAREN,
  [2046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_true,
  [2053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_LBRACE,
  [2060] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_LPAREN,
  [2067] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      anon_sym_payload,
  [2074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_LBRACE,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_SEMI,
  [2088] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      sym_identifier,
  [2095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(385), 1,
      anon_sym_COLON,
  [2102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_COLON,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      anon_sym_SEMI,
  [2116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(391), 1,
      anon_sym_COLON,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_fn,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_LBRACE,
  [2137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      sym_identifier,
  [2144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      sym_identifier,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_SEMI,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(403), 1,
      anon_sym_SEMI,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      ts_builtin_sym_end,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(407), 1,
      anon_sym_RPAREN,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(409), 1,
      anon_sym_COMMA,
  [2186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(411), 1,
      sym_identifier,
  [2193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(413), 1,
      anon_sym_LPAREN,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(415), 1,
      anon_sym_LPAREN,
  [2207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(417), 1,
      sym_identifier,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(419), 1,
      anon_sym_SEMI,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(421), 1,
      anon_sym_false,
  [2228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(423), 1,
      anon_sym_COLON,
  [2235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(425), 1,
      sym_identifier,
  [2242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(427), 1,
      anon_sym_RBRACK,
  [2249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(429), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 70,
  [SMALL_STATE(4)] = 121,
  [SMALL_STATE(5)] = 172,
  [SMALL_STATE(6)] = 209,
  [SMALL_STATE(7)] = 245,
  [SMALL_STATE(8)] = 274,
  [SMALL_STATE(9)] = 303,
  [SMALL_STATE(10)] = 330,
  [SMALL_STATE(11)] = 348,
  [SMALL_STATE(12)] = 372,
  [SMALL_STATE(13)] = 396,
  [SMALL_STATE(14)] = 420,
  [SMALL_STATE(15)] = 444,
  [SMALL_STATE(16)] = 468,
  [SMALL_STATE(17)] = 492,
  [SMALL_STATE(18)] = 517,
  [SMALL_STATE(19)] = 539,
  [SMALL_STATE(20)] = 561,
  [SMALL_STATE(21)] = 583,
  [SMALL_STATE(22)] = 605,
  [SMALL_STATE(23)] = 618,
  [SMALL_STATE(24)] = 633,
  [SMALL_STATE(25)] = 646,
  [SMALL_STATE(26)] = 659,
  [SMALL_STATE(27)] = 677,
  [SMALL_STATE(28)] = 695,
  [SMALL_STATE(29)] = 713,
  [SMALL_STATE(30)] = 731,
  [SMALL_STATE(31)] = 749,
  [SMALL_STATE(32)] = 767,
  [SMALL_STATE(33)] = 778,
  [SMALL_STATE(34)] = 789,
  [SMALL_STATE(35)] = 800,
  [SMALL_STATE(36)] = 811,
  [SMALL_STATE(37)] = 822,
  [SMALL_STATE(38)] = 833,
  [SMALL_STATE(39)] = 844,
  [SMALL_STATE(40)] = 855,
  [SMALL_STATE(41)] = 866,
  [SMALL_STATE(42)] = 877,
  [SMALL_STATE(43)] = 888,
  [SMALL_STATE(44)] = 899,
  [SMALL_STATE(45)] = 910,
  [SMALL_STATE(46)] = 921,
  [SMALL_STATE(47)] = 932,
  [SMALL_STATE(48)] = 943,
  [SMALL_STATE(49)] = 954,
  [SMALL_STATE(50)] = 965,
  [SMALL_STATE(51)] = 976,
  [SMALL_STATE(52)] = 989,
  [SMALL_STATE(53)] = 1000,
  [SMALL_STATE(54)] = 1011,
  [SMALL_STATE(55)] = 1022,
  [SMALL_STATE(56)] = 1036,
  [SMALL_STATE(57)] = 1050,
  [SMALL_STATE(58)] = 1066,
  [SMALL_STATE(59)] = 1080,
  [SMALL_STATE(60)] = 1094,
  [SMALL_STATE(61)] = 1108,
  [SMALL_STATE(62)] = 1122,
  [SMALL_STATE(63)] = 1138,
  [SMALL_STATE(64)] = 1154,
  [SMALL_STATE(65)] = 1168,
  [SMALL_STATE(66)] = 1178,
  [SMALL_STATE(67)] = 1194,
  [SMALL_STATE(68)] = 1210,
  [SMALL_STATE(69)] = 1224,
  [SMALL_STATE(70)] = 1240,
  [SMALL_STATE(71)] = 1254,
  [SMALL_STATE(72)] = 1264,
  [SMALL_STATE(73)] = 1278,
  [SMALL_STATE(74)] = 1292,
  [SMALL_STATE(75)] = 1306,
  [SMALL_STATE(76)] = 1320,
  [SMALL_STATE(77)] = 1336,
  [SMALL_STATE(78)] = 1350,
  [SMALL_STATE(79)] = 1364,
  [SMALL_STATE(80)] = 1378,
  [SMALL_STATE(81)] = 1391,
  [SMALL_STATE(82)] = 1404,
  [SMALL_STATE(83)] = 1417,
  [SMALL_STATE(84)] = 1430,
  [SMALL_STATE(85)] = 1443,
  [SMALL_STATE(86)] = 1456,
  [SMALL_STATE(87)] = 1469,
  [SMALL_STATE(88)] = 1482,
  [SMALL_STATE(89)] = 1493,
  [SMALL_STATE(90)] = 1506,
  [SMALL_STATE(91)] = 1519,
  [SMALL_STATE(92)] = 1532,
  [SMALL_STATE(93)] = 1545,
  [SMALL_STATE(94)] = 1558,
  [SMALL_STATE(95)] = 1571,
  [SMALL_STATE(96)] = 1584,
  [SMALL_STATE(97)] = 1597,
  [SMALL_STATE(98)] = 1610,
  [SMALL_STATE(99)] = 1620,
  [SMALL_STATE(100)] = 1628,
  [SMALL_STATE(101)] = 1636,
  [SMALL_STATE(102)] = 1644,
  [SMALL_STATE(103)] = 1652,
  [SMALL_STATE(104)] = 1660,
  [SMALL_STATE(105)] = 1668,
  [SMALL_STATE(106)] = 1676,
  [SMALL_STATE(107)] = 1686,
  [SMALL_STATE(108)] = 1696,
  [SMALL_STATE(109)] = 1704,
  [SMALL_STATE(110)] = 1714,
  [SMALL_STATE(111)] = 1722,
  [SMALL_STATE(112)] = 1732,
  [SMALL_STATE(113)] = 1740,
  [SMALL_STATE(114)] = 1750,
  [SMALL_STATE(115)] = 1758,
  [SMALL_STATE(116)] = 1766,
  [SMALL_STATE(117)] = 1774,
  [SMALL_STATE(118)] = 1784,
  [SMALL_STATE(119)] = 1792,
  [SMALL_STATE(120)] = 1802,
  [SMALL_STATE(121)] = 1810,
  [SMALL_STATE(122)] = 1818,
  [SMALL_STATE(123)] = 1828,
  [SMALL_STATE(124)] = 1836,
  [SMALL_STATE(125)] = 1843,
  [SMALL_STATE(126)] = 1850,
  [SMALL_STATE(127)] = 1857,
  [SMALL_STATE(128)] = 1864,
  [SMALL_STATE(129)] = 1871,
  [SMALL_STATE(130)] = 1878,
  [SMALL_STATE(131)] = 1885,
  [SMALL_STATE(132)] = 1892,
  [SMALL_STATE(133)] = 1899,
  [SMALL_STATE(134)] = 1906,
  [SMALL_STATE(135)] = 1913,
  [SMALL_STATE(136)] = 1920,
  [SMALL_STATE(137)] = 1927,
  [SMALL_STATE(138)] = 1934,
  [SMALL_STATE(139)] = 1941,
  [SMALL_STATE(140)] = 1948,
  [SMALL_STATE(141)] = 1955,
  [SMALL_STATE(142)] = 1962,
  [SMALL_STATE(143)] = 1969,
  [SMALL_STATE(144)] = 1976,
  [SMALL_STATE(145)] = 1983,
  [SMALL_STATE(146)] = 1990,
  [SMALL_STATE(147)] = 1997,
  [SMALL_STATE(148)] = 2004,
  [SMALL_STATE(149)] = 2011,
  [SMALL_STATE(150)] = 2018,
  [SMALL_STATE(151)] = 2025,
  [SMALL_STATE(152)] = 2032,
  [SMALL_STATE(153)] = 2039,
  [SMALL_STATE(154)] = 2046,
  [SMALL_STATE(155)] = 2053,
  [SMALL_STATE(156)] = 2060,
  [SMALL_STATE(157)] = 2067,
  [SMALL_STATE(158)] = 2074,
  [SMALL_STATE(159)] = 2081,
  [SMALL_STATE(160)] = 2088,
  [SMALL_STATE(161)] = 2095,
  [SMALL_STATE(162)] = 2102,
  [SMALL_STATE(163)] = 2109,
  [SMALL_STATE(164)] = 2116,
  [SMALL_STATE(165)] = 2123,
  [SMALL_STATE(166)] = 2130,
  [SMALL_STATE(167)] = 2137,
  [SMALL_STATE(168)] = 2144,
  [SMALL_STATE(169)] = 2151,
  [SMALL_STATE(170)] = 2158,
  [SMALL_STATE(171)] = 2165,
  [SMALL_STATE(172)] = 2172,
  [SMALL_STATE(173)] = 2179,
  [SMALL_STATE(174)] = 2186,
  [SMALL_STATE(175)] = 2193,
  [SMALL_STATE(176)] = 2200,
  [SMALL_STATE(177)] = 2207,
  [SMALL_STATE(178)] = 2214,
  [SMALL_STATE(179)] = 2221,
  [SMALL_STATE(180)] = 2228,
  [SMALL_STATE(181)] = 2235,
  [SMALL_STATE(182)] = 2242,
  [SMALL_STATE(183)] = 2249,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(177),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(174),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(176),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(175),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(165),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(177),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_basic_block_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 7, 0, 10),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 3, 0, 7),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 9, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 6, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 8, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_fn, 8, 0, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 7, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_fn, 7, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 5, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 10, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 5, 0, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_decl, 4, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 4, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_decl, 6, 0, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_fn, 6, 0, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(155),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat2, 2, 0, 0), SHIFT_REPEAT(164),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat2, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_decl_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(166),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_decl_repeat1, 2, 0, 0),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(183),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_decl_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_repeat1, 2, 0, 0),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extern_fn_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extern_fn_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_switchEnum_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_switchEnum_repeat1, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_block, 4, 0, 4),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 13, 0, 13),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminator, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 8, 0, 9),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switch_case, 3, 0, 11),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 7, 0, 9),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markers, 1, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_block, 3, 0, 4),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_switchEnum, 6, 0, 9),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 2, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goto, 2, 0, 5),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_decl, 3, 0, 3),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_variant, 3, 0, 3),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 3),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_decl, 4, 0, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 1, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 6),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markers, 2, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 8),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 8),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6, 0, 8),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(173),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [405] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(178),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(179),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [419] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rvalue, 6, 0, 12),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(180),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(181),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(182),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_silica_mir(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
